import type { ModelUploadCategory } from '../runware/types'

// Runware's allowed `architecture` values per upload category — see
// https://runware.ai/docs/platform/model-upload
export const UPLOAD_MODEL_ARCHITECTURES: Record<ModelUploadCategory, string[]> = {
  checkpoint: [
    'exactlyai_image',
    'flux1d',
    'flux1s',
    'fluxkontextdev',
    'illustrious',
    'noobai',
    'pony',
    'sd1x',
    'sdxl',
    'sdxllightning',
    'sdxlturbo',
    'z_image',
    'z_image_turbo',
  ],
  lora: [
    'flux1d',
    'flux1s',
    'flux2klein_4b',
    'flux2klein_9b',
    'flux2klein_base_4b',
    'flux2klein_base_9b',
    'flux_2_dev',
    'fluxkontextdev',
    'hidreamdev',
    'hidreamfast',
    'hidreamfull',
    'illustrious',
    'ltx_2_3_video',
    'noobai',
    'pony',
    'qwen_image',
    'qwen_image_edit',
    'qwen_image_edit_plus',
    'qwen_image_layered',
    'sd1x',
    'sd3',
    'sdxl',
    'sdxllightning',
    'sdxlturbo',
    'z_image',
    'z_image_turbo',
  ],
  lycoris: [
    'flux1d',
    'flux1s',
    'flux2klein_4b',
    'flux2klein_9b',
    'flux2klein_base_4b',
    'flux2klein_base_9b',
    'flux_2_dev',
    'fluxkontextdev',
    'hidreamdev',
    'hidreamfast',
    'hidreamfull',
    'illustrious',
    'noobai',
    'pony',
    'qwen_image',
    'qwen_image_edit',
    'qwen_image_edit_plus',
    'qwen_image_layered',
    'sd1x',
    'sd3',
    'sdxl',
    'sdxllightning',
    'sdxlturbo',
    'z_image',
    'z_image_turbo',
  ],
  vae: ['illustrious', 'noobai', 'pony', 'sd1x', 'sdxl', 'sdxllightning', 'sdxlturbo'],
  embeddings: ['illustrious', 'noobai', 'pony', 'sd1x', 'sdxl', 'sdxllightning', 'sdxlturbo'],
}

export const UPLOAD_MODEL_CATEGORY_LABELS: Record<ModelUploadCategory, string> = {
  checkpoint: 'Checkpoint',
  lora: 'LoRA',
  lycoris: 'LyCORIS',
  vae: 'VAE',
  embeddings: 'Embeddings',
}
